package cmd

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/zinwaishine/super-agent/internal/config"
	"github.com/zinwaishine/super-agent/internal/database"
	"github.com/zinwaishine/super-agent/internal/playwright"
)

var postCmd = &cobra.Command{
	Use:   "post",
	Short: "Post a prepped listing to Facebook Marketplace or Pages",
	RunE: func(cmd *cobra.Command, args []string) error {
		listingID, _ := cmd.Flags().GetString("id")
		target, _ := cmd.Flags().GetString("target")
		headless, _ := cmd.Flags().GetBool("headless")
		dryRun, _ := cmd.Flags().GetBool("dry-run")
		pageID, _ := cmd.Flags().GetString("page-id")
		targetURL, _ := cmd.Flags().GetString("url")

		cfg, err := config.Load()
		if err != nil {
			return fmt.Errorf("failed to load config: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		db, err := database.New(ctx, config.DatabaseConfig{
			URL: cfg.Database.URL, MaxOpenConns: 5, MaxIdleConns: 2, ConnMaxLifetime: "5m",
		})
		if err != nil || cfg.Database.URL == "" {
			return fmt.Errorf("database connection failed: %v", err)
		}
		defer db.Close()

		reader := bufio.NewReader(os.Stdin)

		var thBody string
		var images []string

		// 1. TOP-LEVEL POST MODE SELECTION
		mode := "database"
		if listingID == "" {
			fmt.Println("\n🚀 How would you like to post?")
			fmt.Println("   1) Post from Database (Prepped Listings)")
			fmt.Println("   2) Manual Post (Provide image folder and text)")
			fmt.Print("👉 Select option (1-2) [default: 1]: ")

			opt, _ := reader.ReadString('\n')
			opt = strings.TrimSpace(opt)
			if opt == "2" {
				mode = "manual"
			}
		}

		if mode == "database" {
			// 1A. INTERACTIVE LISTING SELECTION
			if listingID == "" {
				fmt.Println("\n📋 Looking up recently prepped listings from your database...")
				rows, err := db.Pool.Query(ctx, "SELECT id, title FROM listings WHERE status = 'prepped' ORDER BY created_at DESC LIMIT 5")
				if err == nil {
					var ids []string
					i := 1
					for rows.Next() {
						var id, title string
						if err := rows.Scan(&id, &title); err == nil {
							fmt.Printf("   %d) %s\n", i, title)
							ids = append(ids, id)
							i++
						}
					}
					rows.Close()

					if len(ids) > 0 {
						fmt.Print("\n👉 Select a listing to post (1-", len(ids), "), or paste a full UUID: ")
						input, _ := reader.ReadString('\n')
						input = strings.TrimSpace(input)
						var choice int
						if _, err := fmt.Sscanf(input, "%d", &choice); err == nil && choice > 0 && choice <= len(ids) {
							listingID = ids[choice-1]
						} else if input != "" {
							listingID = input
						}
					}
				}
				if listingID == "" {
					return fmt.Errorf("no listing selected. You must provide a valid ID")
				}
			}

			// Load data from DB
			err = db.Pool.QueryRow(ctx, "SELECT body FROM listing_content WHERE listing_id = $1 AND language = 'th'", listingID).Scan(&thBody)
			if err != nil {
				fmt.Println("⚠️  Could not find Thai prepped content in database. Did you run 'super-agent prep' first?")
				fmt.Println("   Using fallback dummy text.")
				thBody = fmt.Sprintf("Amazing Property Listing #%s\n\nContact us for details! (This is an automated post generated by Super-Agent)", listingID)
			}

			// Scan the staging/ folder
			cwd, _ := os.Getwd()
			files, err := os.ReadDir("staging")
			if err == nil {
				for _, f := range files {
					if !f.IsDir() && (strings.HasSuffix(f.Name(), ".jpg") || strings.HasSuffix(f.Name(), ".png")) {
						images = append(images, filepath.Join(cwd, "staging", f.Name()))
						if len(images) >= 4 {
							break // limit to 4 to prevent fb overload initially
						}
					}
				}
			}

		} else {
			// 1B. MANUAL POST SELECTION
			fmt.Println("\n📂 Step 1: Image Folder")
			fmt.Println("   Where are the images located?")

			defaultPath := "./downloads/"
			if cfg != nil && cfg.App.ImagePath != "" {
				defaultPath = cfg.App.ImagePath
			}
			fmt.Printf("👉 Enter path (Press ENTER for default %s): ", defaultPath)
			input, _ := reader.ReadString('\n')
			input = strings.TrimSpace(input)
			folderPath := defaultPath
			if input != "" {
				folderPath = input
			}

			// Load images from the folder
			files, err := os.ReadDir(folderPath)
			if err == nil {
				for _, f := range files {
					if !f.IsDir() && (strings.HasSuffix(strings.ToLower(f.Name()), ".jpg") || strings.HasSuffix(strings.ToLower(f.Name()), ".png") || strings.HasSuffix(strings.ToLower(f.Name()), ".jpeg")) {
						absPath, _ := filepath.Abs(filepath.Join(folderPath, f.Name()))
						images = append(images, absPath)
						if len(images) >= 20 { // More forgiving limit for manual mode
							break
						}
					}
				}
			} else {
				fmt.Printf("⚠️  Could not read directory %s: %v\n", folderPath, err)
			}
			fmt.Printf("   ✅ Found %d images.\n", len(images))

			fmt.Println("\n📝 Step 2: Post Content")
			fmt.Println("   Paste or type your post content below.")
			fmt.Println("   (Type 'END' on a new line and press Enter when finished):")
			var lines []string
			for {
				line, _ := reader.ReadString('\n')
				if strings.TrimSpace(line) == "END" {
					break
				}
				lines = append(lines, line)
			}
			thBody = strings.Join(lines, "")
			if strings.TrimSpace(thBody) == "" {
				thBody = "Beautiful property available now! Contact us for details. #property #realestate"
			}
		}

		// 2. INTERACTIVE TARGET SELECTION & GUIDE
		if target == "" && pageID == "" && targetURL == "" {
			fmt.Println("\n📍 Where would you like to post this listing?")
			fmt.Println("   1) Facebook Page (Standard - using your page username)")
			fmt.Println("   2) Meta Business Suite (Advanced - skipping directly to Business Suite)")
			fmt.Println("   3) Facebook Marketplace (Standard)")
			fmt.Print("👉 Choose an option (1-3): ")

			opt, _ := reader.ReadString('\n')
			opt = strings.TrimSpace(opt)

			switch opt {
			case "1":
				target = "pages"
				fmt.Print("   Enter your Facebook Page Username (e.g. dediaxdigitalbusiness): ")
				pageID, _ = reader.ReadString('\n')
				pageID = strings.TrimSpace(pageID)
				fmt.Println("\n=============================================")
				fmt.Println("📘 THE PLAYBOOK: Standard Facebook Page")
				fmt.Println("=============================================")
				fmt.Println("1. The browser will open to your public Facebook Page view.")
				fmt.Println("2. If the 'Create Post' box is visible, the bot will click it automatically.")
				fmt.Println("3. If it is NOT visible (common with new Facebook layouts), the bot will pause.")
				fmt.Println("4. If it pauses, you should manually switch profiles or click 'Create Post'.")

			case "2":
				target = "pages"
				defaultURL := ""
				if cfg != nil && cfg.Facebook.BusinessURL != "" {
					defaultURL = cfg.Facebook.BusinessURL
				}

				if defaultURL != "" {
					fmt.Printf("   Enter your copied Meta Business Suite URL (Press ENTER for default %s): ", defaultURL)
				} else {
					fmt.Print("   Enter your copied Meta Business Suite URL: ")
				}
				targetURL, _ = reader.ReadString('\n')
				targetURL = strings.TrimSpace(targetURL)

				if targetURL == "" && defaultURL != "" {
					targetURL = defaultURL
				}
				fmt.Println("\n=============================================")
				fmt.Println("📘 THE PLAYBOOK: Meta Business Suite")
				fmt.Println("=============================================")
				fmt.Println("1. The browser will open directly to your Business Suite Dashboard.")
				fmt.Println("2. Because Business Suite changes constantly, the bot will IMMEDIATELY PAUSE.")
				fmt.Println("3. YOU must manually click the blue 'Create Post' button in the browser.")
				fmt.Println("4. Once the 'Create Post' modal opens on the screen, press ENTER here in the terminal.")
				fmt.Println("5. The bot will wake up, attach photos, and type the AI text into the box!")

			case "3":
				target = "marketplace"
				fmt.Println("\n=============================================")
				fmt.Println("📘 THE PLAYBOOK: Facebook Marketplace")
				fmt.Println("=============================================")
				fmt.Println("1. The bot will open Facebook Marketplace.")

			default:
				fmt.Println("Invalid choice, defaulting to Marketplace.")
				target = "marketplace"
			}

			fmt.Print("\nReady? Press ENTER to launch the browser...")
			reader.ReadString('\n')
		}

		if listingID != "" {
			fmt.Printf("\n📤 Booting Sniper Bot for Listing: %s\n", listingID)
		} else {
			fmt.Printf("\n📤 Booting Sniper Bot for Manual Post\n")
		}
		if dryRun {
			fmt.Println("   🧪 TEST MODE ENABLED: The bot will NOT click Publish.")
		} else {
			fmt.Println("   💥 LIVE MODE ENABLED: The bot WILL click Publish.")
		}
		if !headless {
			fmt.Println("   👁  Running in visible browser mode.")
		}

		err = playwright.PostListing(playwright.PostOptions{
			Target:    target,
			PageID:    pageID,
			TargetURL: targetURL,
			Content:   thBody,
			Images:    images,
			Headless:  headless,
			DryRun:    dryRun,
		})
		if err != nil {
			return fmt.Errorf("\n❌ Playwright automation failed: %w", err)
		}

		return nil
	},
}

// RunAutoPostFlow handles the automatic post sequence after a download finishes.
// It loads images from the folder, asks only for content (with empty defaults),
// targets Business Suite by default, and publishes.
func RunAutoPostFlow(folderPath string, headless bool, dryRun bool) error {
	cfg, err := config.Load()
	if err != nil {
		fmt.Printf("⚠️  Warning: could not load config (%v)\n", err)
	}
	reader := bufio.NewReader(os.Stdin)
	var images []string
	var thBody string

	// 1. Auto load images from folderPath
	files, err := os.ReadDir(folderPath)
	if err == nil {
		for _, f := range files {
			if !f.IsDir() && (strings.HasSuffix(strings.ToLower(f.Name()), ".jpg") || strings.HasSuffix(strings.ToLower(f.Name()), ".png") || strings.HasSuffix(strings.ToLower(f.Name()), ".jpeg")) {
				absPath, _ := filepath.Abs(filepath.Join(folderPath, f.Name()))
				images = append(images, absPath)
				if len(images) >= 20 {
					break // Cap to 20 images
				}
			}
		}
	} else {
		fmt.Printf("⚠️  Could not read directory %s: %v\n", folderPath, err)
	}
	fmt.Printf("   ✅ Auto-loaded %d images from %s.\n", len(images), folderPath)

	// 2. Ask ONLY for content
	fmt.Println("\n📝 Step 2: Post Content")
	fmt.Println("   Paste or type your post content below.")
	fmt.Println("   (Type 'END' on a new line and press Enter when finished):")
	var lines []string
	for {
		line, _ := reader.ReadString('\n')
		if strings.TrimSpace(line) == "END" {
			break
		}
		lines = append(lines, line)
	}
	thBody = strings.Join(lines, "")
	if strings.TrimSpace(thBody) == "" {
		thBody = "Beautiful property available now! Contact us for details. #property #realestate"
	}

	// 3. Auto-Select Target 2 (Business Suite)
	target := "pages"
	targetURL := ""
	pageID := ""

	if cfg != nil && cfg.Facebook.BusinessURL != "" {
		targetURL = cfg.Facebook.BusinessURL
		fmt.Printf("\n⚡ Auto-selecting Meta Business Suite Target: %s\n", targetURL)
	} else {
		fmt.Println("\n⚠️  No Default Business Facebook URL found in settings.")
		fmt.Print("   Enter your copied Meta Business Suite URL: ")
		tURL, _ := reader.ReadString('\n')
		targetURL = strings.TrimSpace(tURL)
	}

	fmt.Printf("\n📤 Booting Sniper Bot for Auto-Post (Images: %d)\n", len(images))
	if dryRun {
		fmt.Println("   🧪 TEST MODE ENABLED: The bot will NOT click Publish.")
	} else {
		fmt.Println("   💥 LIVE MODE ENABLED: The bot WILL click Publish.")
	}
	if !headless {
		fmt.Println("   👁  Running in visible browser mode.")
	}

	err = playwright.PostListing(playwright.PostOptions{
		Target:    target,
		PageID:    pageID,
		TargetURL: targetURL,
		Content:   thBody,
		Images:    images,
		Headless:  headless,
		DryRun:    dryRun,
		AutoPost:  true,
	})

	if err == nil {
		fmt.Println("\n🧹 Cleaning up: Deleting posted images from default folder...")
		var deleted int
		for _, img := range images {
			if e := os.Remove(img); e == nil {
				deleted++
			}
		}
		fmt.Printf("   🗑  Deleted %d images.\n", deleted)
	}

	return err
}

func init() {
	rootCmd.AddCommand(postCmd)

	postCmd.Flags().String("id", "", "listing ID to post")
	postCmd.Flags().String("target", "", "target: marketplace, pages")
	postCmd.Flags().String("page-id", "", "Facebook page username/ID")
	postCmd.Flags().String("url", "", "Exact URL to target (for Business Suite)")
	postCmd.Flags().Bool("headless", false, "run browser in invisible mode")
	postCmd.Flags().Bool("dry-run", true, "prevent clicking the final publish button")
}
